// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDma8qPL3h8LZ15FxdbXj6f-FHI99xv5Cc',
    appId: '1:565106634867:web:5b5e60114f02f4e3c9ba06',
    messagingSenderId: '565106634867',
    projectId: 'flutter-todo-lab-81e79',
    authDomain: 'flutter-todo-lab-81e79.firebaseapp.com',
    storageBucket: 'flutter-todo-lab-81e79.appspot.com',
    measurementId: 'G-VQPXGNPNKE',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdZ8wrngqXvE0kiTylxKe5JaWxkLf16PA',
    appId: '1:565106634867:ios:46443e46ef8530d5c9ba06',
    messagingSenderId: '565106634867',
    projectId: 'flutter-todo-lab-81e79',
    storageBucket: 'flutter-todo-lab-81e79.appspot.com',
    iosBundleId: 'com.example.flutterTodoLab2',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdZ8wrngqXvE0kiTylxKe5JaWxkLf16PA',
    appId: '1:565106634867:ios:46443e46ef8530d5c9ba06',
    messagingSenderId: '565106634867',
    projectId: 'flutter-todo-lab-81e79',
    storageBucket: 'flutter-todo-lab-81e79.appspot.com',
    iosBundleId: 'com.example.flutterTodoLab2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaYP1gg_eTiILiExsgepLZnszYfBFzs3g',
    appId: '1:565106634867:android:bbb312a2bb939baac9ba06',
    messagingSenderId: '565106634867',
    projectId: 'flutter-todo-lab-81e79',
    storageBucket: 'flutter-todo-lab-81e79.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDma8qPL3h8LZ15FxdbXj6f-FHI99xv5Cc',
    appId: '1:565106634867:web:79e379cde9c538a6c9ba06',
    messagingSenderId: '565106634867',
    projectId: 'flutter-todo-lab-81e79',
    authDomain: 'flutter-todo-lab-81e79.firebaseapp.com',
    storageBucket: 'flutter-todo-lab-81e79.appspot.com',
    measurementId: 'G-45FZ1Y7WCW',
  );

}